{% set name = "oauthenticator" %}
{% set version = "14.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4baa02ff2c159cbba06f8d07fe11a6e624285ca2f813b1258b4c68766c0ee46b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyterhub >=0.5

test:
  imports:
    - oauthenticator

about:
  home: https://github.com/jupyterhub/oauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OAuth + JupyterHub Authenticator = OAuthenticator

  doc_url: https://jhubdocs.readthedocs.io/en/latest/oauthenticator/
  dev_url: https://github.com/jupyterhub/oauthenticator

extra:
  recipe-maintainers:
    - ericcina
    - sodre
    - consideRatio
