{% set name = "oauthenticator" %}
{% set version = "17.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5d90cb2411fff3dc6fcc1633468233c0e0e0239422c087c7734d1685055b8f3

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps . -vv

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/setup.py
    # ref: https://github.com/jupyterhub/oauthenticator/blob/main/requirements.txt
    - python >=3.8
    - jsonschema
    - jupyterhub >=2.2
    - pyjwt >=2
    - requests
    - ruamel.yaml
    - tornado
    - traitlets

test:
  imports:
    - oauthenticator

about:
  home: https://github.com/jupyterhub/oauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OAuth + JupyterHub Authenticator = OAuthenticator
  doc_url: https://jhubdocs.readthedocs.io/en/latest/oauthenticator/
  dev_url: https://github.com/jupyterhub/oauthenticator

extra:
  recipe-maintainers:
    - ericcina
    - sodre
    - consideRatio
